pipeline 
{
  environment 
  {
    registry = "guevavil/mavenapp"
    registryCredential = 'dockerhub'
  }
  agent 
  {
    docker 
    {
       image 'maven:3-alpine' 
       args '-v /tmp/:/root/.m2' 
    }
  }
  stages 
  {
    stage('SCM') 
    {
      steps
      {
        git 'https://github.com/ruben-arenas/simple-java-maven-app.git'
      }
    }
    stage('Build') 
    { 
      steps 
      {
        sh 'mvn -B -DskipTests clean package' 
      }
    }
    stage('Test') 
    { 
      steps 
      {
        sh 'mvn test' 
      }
      post 
      {
        always
	{
          junit 'target/surefire-reports/*.xml' 
        }
      }
    }
     stage('Deploy') 
     {
       steps 
       {
         sh 'docker build -t guevavil/mavenapp:latest .'
       }
     }
   }
}

