pipeline 
{
  environment 
  {
    registry = "guevavil/mavenapp"
    registryCredential = 'dockerhub'
  }
  agent 
  {
    docker 
    {
       image 'maven:3.5.0' 
       args '-v /root/.m2:/root/.m2' 
    }
  }
  stages 
  {
    stage('SCM') 
    {
      steps
      {
        git branch: "main", url: 'https://github.com/ruben-arenas/simple-java-maven-app.git'
      }
    }
    stage('Build') 
    { 
      steps 
      {
        sh 'mvn -B -DskipTests clean package' 
      }
    }
    stage('Test') 
    { 
      steps 
      {
        sh 'mvn test' 
      }
      post 
      {
        always
	{
          junit 'target/surefire-reports/*.xml' 
        }
      }
    }
     stage('Build Docker Image') 
    {
      steps 
      {
        echo '=== Building Maven Docker Image ==='
        script {
          docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy') 
    {
       steps 
       {
         echo '=== Pushing Maven Docker Image ==='
         script {
          docker.push registry + ":$BUILD_NUMBER"
        }
       }
     }
   
   }
}

