pipeline 
{
  environment 
  {
    registry = "guevavil/mavenapp"
    registryCredential = 'docker-hub_user'
  }
  agent 
  {
    docker 
    {
       image 'maven:3-alpine' 
       args '--net=jenkins_net -v /root/.m2:/root/.m2' 
    }
  }
  stages 
  {
    stage('SCM') 
    {
      steps
      {
        git credentialsId: 'gitlab-user',
        url: 'http://git-server/jenkins/simple-java-maven-app.git'
      }
    }
    stage('Build') 
    { 
      steps 
      {
        sh 'mvn -B -DskipTests clean package' 
      }
    }
    stage('Test') 
    { 
      steps 
      {
        sh 'mvn test' 
      }
      post 
      {
        always
	{
          junit 'target/surefire-reports/*.xml' 
        }
      }
    }
    stage('Sonar-scanner') 
    { 
      steps 
      {
        withSonarQubeEnv('SonnarQubeServer') 
	{
          sh 'mvn clean package sonar:sonar'
        }
       }
     }
     stage('Deploy') 
     {
       steps 
       {
         sh 'docker build -t guevavil/mavenapp:latest .'
       }
     }
   }
}

