pipeline 
{
  agent none
  stages 
  {
    stage('build and test') 
    {
      agent 
      {
        docker 
        {
          image 'maven:3.6.3-jdk-8' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps 
      {
        git branch: "main", url: 'https://github.com/ruben-arenas/maven-web-app.git'
        sh 'mvn package' 
      }
    }
    stage('deploy') 
    {
      agent any
      environment 
      {
        registry = "guevavil/mavenapp"
        registryCredential = 'dockerhub'
        BUILD_NUMBER_BASE = '0'
        VERSION_MAJOR = '0'
        VERSION_MINOR = '1'
        VERSION_PATCH = "${env.BUILD_NUMBER.toInteger() - BUILD_NUMBER_BASE.toInteger()}"
      }
      steps 
      {
        echo '=== Building Maven Docker Image ==='
        def foo = sh(script: 'pwd', returnStdout: true)
        echo ${foo}
        script 
        {
          docker.withRegistry( '', registryCredential ) 
          {
            def dockerImage = docker.build registry + ":$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH -f maven-web/Dockerfile"
            dockerImage.push()
          }
        }
      }
    }
  }
}