pipeline 
{
  agent none
  stages 
  {
    stage('build and test') 
    {
      agent 
      {
        docker 
        {
          image 'maven:3.6.3-jdk-8' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps 
      {
        git branch: "main", url: 'https://github.com/ruben-arenas/maven-web-app.git'
        sh 'mvn package' 
      }
    }
    stage('deploy') 
    {
      agent any
      environment 
      {
        registry = "guevavil/mavenapp"
        registryCredential = 'dockerhub'
        dockerImage = ''
      }
      steps 
      {
        echo '=== Building Maven Docker Image ==='
        script {
          def scriptPath = currentBuild.rawBuild.parent.definition.scriptPath
          dockerImage = docker.build registry + ":$BUILD_NUMBER -f ${scriptPath}/Dockerfile"
          docker.withRegistry( '', registryCredential ) 
          {
            dockerImage.push()
          }
        }
      }
    }
  }
}